# Generated by Django 4.0.3 on 2022-03-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('date_of_employment', models.DateField(verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер заработной платы')),
                ('salary_paid', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Информация о выплаченной зарплате')),
                ('level', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='4', max_length=1, verbose_name='Уровень иерархии')),
                ('chief', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='workers_app.employee', verbose_name='Начальник')),
            ],
        ),
    ]
